# Generated by Django 2.2.5 on 2022-03-22 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0002_auto_20220321_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversations',
            new_name='Conversation',
        ),
    ]
